### ISSUE TITLE
Question regarding fields in json configuration

### ISSUE THREAD

**Issue by renadi** [AgriCraft/AgriPlants#25]
I'm looking for some clarification of what certain fields mean in the json configs.

Most importantly, what does the required field in the products do, because it has a chance(generally around 90%) but also a required field which obviously doesn't mean that result is required. as you can have multiple required and still only get one of the products.

What I'm specifically trying to do is add a .01% chance of seeds dropping as well as a 1% chance of Roots Verdant Sprigs.

on 1.10.2.

**Comment by CodesCubesAndCrashes** [comment]
I think this it's a full answer, but I'm not an expert. The required field determines if this plant should be loaded even if that particular product is not valid in the current setup. For example, if Verdant Sprigs don't exist (maybe Roots isn't installed), and `required` is true, then this plant will be disabled. And if it's set to false, then the Sprigs will be removed as a drop but the plant will still loaded. 

Also, please mentioned which version of AgriCraft for 1.10.2 you are testing. Is it a17, a18, or a different one?

**Comment by renadi** [comment]
A17, I'll test it and see if that works, but I like the sound of that,
makes me think the configs for verdant sprigs could be added to default
configs without breaking everything then.

**Comment by TokkenGmr** [comment]
Here is an example of nether wart dropping [infernal bulb](https://pastebin.com/YSAVwVpy) not sure if this will help or not

**Comment by InfinityRaider** [comment]
This seems to be answered correctly by @CodesCubesAndCrashes
