### ISSUE TITLE
Duplicate ids

### ISSUE THREAD

**Issue by bibo38** [AgriCraft/AgriPlants#27]
I have just searched this repository for duplicate IDs and found the following:
- [ ] coffee_plant
- [ ] rice_plant
- [ ] barley_plant
- [ ] cotton_plant
- [ ] beet_plant
- [x] farmland_soil

Instead of just renaming every plant, I would suggest a namespace feature.
Example usage may be:
- When referencing a plant, we just use the current folder as the namespace. E.g. Referencing beet_plant in the vanilla folder leads to the search for "vanilla:beet_plant"
- Referencing from other mods may be like "harvestcraft:beet_plant" or "vanilla:beet_plant"

**Comment by RlonRyan** [comment]
Yeah... I really should add domains to the loader.

**Comment by TokkenGmr** [comment]
A PR has been made that removes the extra farmland_soil JSON. As well as a change to the vanilla beet JSON that will eliminate those duplicates
