### ISSUE TITLE
Tulip plant ids don't match file names.

### ISSUE THREAD

**Issue by Dilnu** [AgriCraft/AgriPlants#28]
if you look in white_tulip_plant.json and others the id is whitetulip_plant this is unexpected and should be fixed.

**Comment by InfinityRaider** [comment]
I'm not sure I'm following you here, what exactly do you mean?

**Comment by TokkenGmr** [comment]
@InfinityRaider There was a reformat that happened 2 months back that changed the "path" and it no longer matches the "id" of the plant on those 4 JSON files.

**Comment by Dilnu** [comment]
The issue is that in almost every other plant the file name and the plant id match. The mismatch generates confusion when using them in mutations as has already happened with the botania flower mutations.

**Comment by TokkenGmr** [comment]
@Dilnu I'm not sure I follow you on the botania flower mutations, none of them use the tulip flowers. Unless you are setting your JSONs custom? In which case yes there would be an issue, because they weren't used in mutations as far as I can remember.

**Comment by InfinityRaider** [comment]
Ok from a consistency point of view this makes sense

**Comment by RlonRyan** [comment]
Yeah the plant ids could/should be updated... The issue is that it would cause the removal of the old plants...

**Comment by CodesCubesAndCrashes** [comment]
On the one hand, I'm sure some modpack makers would appreciate having a way to change IDs and keep games saves intact. 

On the other hand, this is such a rare occurrence that having special loading code for it seems excessive. And in this particular update, it's for a mod that's still in Alpha. 

If it helps, I think that making a note on the changelog warning users that tulips will vanish from crops and their `AgriSeed`s will be useless is more than adequate for an Alpha.
