### ISSUE TITLE
Agricultural Expansion 

### ISSUE THREAD

**Issue by renadi** [AgriCraft/AgriPlants#31]
I did a quick find-replace for all the mystical agricultural items replacing them with the Agricultural Expansion versions, would I upload it here  or do you expect more work be put into generating the files?

I have so far made no changes other than the find-replace and removing the plants Agricultural Expansion doesn't have.

**Comment by TokkenGmr** [comment]
There is currently a commit for Agricultural Expansion #24. It just needs to be reviewed before it is added.

**Comment by RlonRyan** [comment]
The plants have been added to the next version.
