### ISSUE TITLE
How to Get Item IDs and Names to make Custom Files

### ISSUE THREAD

**Issue by MokahTGS** [AgriCraft/AgriPlants#4]
I'm interested in making JSON files for Mystical agriculture but I'm unsure how to get the required IDs and names needed to make seeds.  Also is there a way to debug what I do?  I'm not a professional and I'm 99.9% sure I will screw this up.

**Comment by Thiana** [comment]
F3+H to enable item ids.

http://minecraft.gamepedia.com/Debug_screen#More_debug-keys
