### ISSUE TITLE
Product from mystical agriculture inferium plant is wrong in json

### ISSUE THREAD

**Issue by RuurdBijlsma** [AgriCraft/AgriPlants#42]
In the files
tier1_inferium_plant.json
tier2_inferium_plant.json
tier3_inferium_plant.json
tier4_inferium_plant.json
tier5_inferium_plant.json

The item id for the product of this plant is mysticalagriculture:inferium_essence, but this item id is now mysticalagriculture:crafting

https://i.imgur.com/VAm3bgM.png

products object should now be:

```
    {
        "min": 1,
        "max": 5,
        "chance": 0.9,
        "required": true,
        "item": "mysticalagriculture:crafting",
        "meta": 0,
        "tags": "",
        "ignoreMeta": false,
        "ignoreTags": [],
        "useOreDict": false
    }
```

**Comment by Noragiri** [comment]
Just here to confirm that it fix the issue :D
