### ISSUE TITLE
IC2 Classic Hemp

### ISSUE THREAD

**Issue by Khitiara** [AgriCraft/AgriPlants#46]
Can we get Ic2 classic hemp as an option? Tried to add it myself but couldnt get it working.
My attempt to work on it is https://gist.github.com/robotbrain/7990f5573cdf059681e0e39b3d4e6cfe if that helps.

**Comment by raziel23x** [comment]
the correct format is mod_ic2 as the folder name and 
do 
 "path": "mod_ic2/plants/hemp_plant.json",

**Comment by robotbrain** [comment]
the path was auto-set when I put it in the folder (was testing this in a pack Im working on as custom stuff)

**Comment by robotbrain** [comment]
thanks for the info though!

**Comment by robotbrain** [comment]
Ok, so got that working - how would I go about using a subset of a texture for the crop texture (ic2 uses a large texture file divided into 16x16 sections, is it possible to reference that in the agriplant?

**Comment by InfinityRaider** [comment]
No, the plant does not allow you to specify UVs, you will have to extract the textxure and add it as a separate sprite.
