### ISSUE TITLE
Add Coal Seeds

### ISSUE THREAD

**Issue by RlonRyan** [AgriCraft/AgriPlants#5]
As per a request in the AgriCraft repository.

**Comment by Tsukiumy** [comment]
[Caralluma speciosa](https://thumbs.dreamstime.com/z/caralluma-speciosa-flower-23698924.jpg)
[Json](https://gist.github.com/Tsukiumy/bb5d67717869ce298dd5e9d31c3413f9)
{block attempts](https://www.dropbox.com/s/5l5dagt7znmvzp5/coal%20seed.rar?dl=0)
pls dont expect somenting that good for textures, i just made a try, but even for me it looks like shit srry

**Comment by InfinityRaider** [comment]
Yes
