### ISSUE TITLE
[2.12.0-1.12.0-a6] Botania flowers json doesn't work.

### ISSUE THREAD

**Issue by PokeMaserJ** [AgriCraft/AgriPlants#50]
So not sure why, but the Botania jsons don't appear to work.

**Comment by Sl0ter** [comment]
I had the same issue.
You just need to change the name mod_Botania folder to mod_botania in config\agricraft\json\defaults

somehow it has problems with a upperlatter

cheers
Sl0ter

**Comment by katubug** [comment]
Thank you for the fix, Sl0ter! This is still present in version AgriCraft-2.12.0-1.12.0-a6

**Comment by Khroz** [comment]
That fix doesn't work for me, it just creates another folder with the B-uppercased files again whenever i rerun the server. I'm using that exact version stated by katubug, AgriCraft-2.12.0-1.12.0-a6

Please i'd like some heads up on how to fix this

**Comment by Sl0ter** [comment]
did you change the folder name from "mod_Botania" to "mod_botania"?

**Comment by Vislor** [comment]
I also corrected the path names inside the files by running the following (using a bash shell) inside the config/agricraft/json/defaults folder.  Not sure if it was needed:

```find mod_botania -type f -print0 | xargs -0 sed -i 's/mod_Botania/mod_botania/g'```

**Comment by Sl0ter** [comment]
the path should be "/(your minecraft folder)/config/agricraft/json/defaults/mod_botania/" not "/json/defaults/mod_Botania/mod_botania/" 
the ubercase caused this error.

**Comment by Diego-Hidra** [comment]
Please can you write the steps to be able to fix this problem in a better way. I got lost after changing the plant paths to "mod_botania", but it automatically generates a "mod_Botania" folder.

**Comment by InfinityRaider** [comment]
Yes, it will regenerate that folder, but it doesn't matter, you can just leave it there and ignore it. As long as there is a folder mod_botania with the jsons, the seeds will get loaded.
