### ISSUE TITLE
excel file for help

### ISSUE THREAD

**Issue by Tsukiumy** [AgriCraft/AgriPlants#7]
just droping a excel file that will help create the jsons for crops
nota perfect but help a lot to start
https://www.dropbox.com/s/bjp5qx0563iecii/test1.xlsm?dl=0
(its a xlsm cuz it has a buton to auto make the .json file with ease)

**Comment by RlonRyan** [comment]
Thanks.

**Comment by InfinityRaider** [comment]
We could put that in the repo or a link to it in the readme
