### ISSUE TITLE
Created JSONs for Vanilla Mutations

### ISSUE THREAD

**Issue by Jo-Mamma75** [AgriCraft/AgriPlants#8]
Please add the following files to the Vanilla Mutations.
If not, at least they're here for someone else to use.

https://pastebin.com/BUEuzP38 (brownshroom_mutation.json)
https://pastebin.com/2rFgzke6 (cactus_mutation.json)
https://pastebin.com/JNJC2Pku (redshroom_mutation.json)
https://pastebin.com/sHkqmrqt (sugarcane_mutation.json)

**Comment by RlonRyan** [comment]
Thanks! Similar default mutations have now been added!
