### ISSUE TITLE
Created json for vanilla flowers

### ISSUE THREAD

**Issue by TokkenGmr** [AgriCraft/AgriPlants#9]
Here are some json files for the vanilla flowers 

[Allium](https://pastebin.com/yEvPqCVB)
[Daisy](https://pastebin.com/S9VkhEWD)
[Dandelion ](https://pastebin.com/dJqX5ZKM)
[Orange Tulip](https://pastebin.com/0tqFpX9g)
[Orchid](https://pastebin.com/EuqNg0fY)
[Pink Tulip](https://pastebin.com/L3s4rpMq)
[Poppy](https://pastebin.com/PdwWYRvc)
[Red Tulip](https://pastebin.com/dJ8iUdFn)
[White Tulip](https://pastebin.com/BadyV2cm)

**Comment by Gkoliver** [comment]
Shouldn't they drop the flowers themselves?

**Comment by TokkenGmr** [comment]
I based it off the 1.7.10 version which gives dye as the drop, kind of the same concept with the Botania crops they give you a petal not the flower. You could change it yourself, it is only just one line in in the above json

**Comment by InfinityRaider** [comment]
Can you make a PR for this?

**Comment by Thiana** [comment]
Didn't the 1.7.10 version drop the flower when you used shears on the cropsticks? Does the json format permit that?

**Comment by TokkenGmr** [comment]
If I remember correctly this was talked about [here](https://github.com/AgriCraft/AgriCraft/issues/219)
Not sure if the current json allows for it or not

**Comment by RlonRyan** [comment]
Moved to #10.
